name: Pipeline Ministerio de Turismo

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Configure long paths
      run: |
        git init
        git config --system core.longpaths true


    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      working-directory: Material Obligatorio/Obligatorio/Ministerio de Turismo
      run: dotnet restore

    - name: Build
      working-directory: Material Obligatorio/Obligatorio/Ministerio de Turismo
      run: dotnet build --no-restore
  
  test:
    needs: build 
    runs-on: windows-latest

    steps:
    - name: Configure long paths
      run: |
        git init
        git config --system core.longpaths true

    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      working-directory: Material Obligatorio/Obligatorio/Ministerio de Turismo
      run: dotnet restore

    - name: Build
      working-directory: Material Obligatorio/Obligatorio/Ministerio de Turismo
      run: dotnet build --no-restore

    - name: Test
      working-directory: Material Obligatorio/Obligatorio/Ministerio de Turismo
      run: dotnet test --no-build --verbosity normal

  build-frontend:
    runs-on: windows-latest

    steps:
    - name: Configure long paths
      run: |
        git init
        git config --system core.longpaths true
    
    - uses: actions/checkout@v3

    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
      
    - name: Install dependencies
      working-directory: Material Obligatorio/Obligatorio/MinTurFrontend
      run: npm ci

    - name: Build FrontEnd
      working-directory: Material Obligatorio/Obligatorio/MinTurFrontend
      run: ng build
