name: .NET

on:
  push:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      working-directory: Material Obligatorio/Obligatorio/Ministerio de Turismo
      run: dotnet restore
    - name: Build
      working-directory: Material Obligatorio/Obligatorio/Ministerio de Turismo
      run: dotnet build --no-restore
    - name: Test
      working-directory: Material Obligatorio/Obligatorio/Ministerio de Turismo
      run: dotnet test --no-build --verbosity normal
