name: Ministerio de Turismo

on:
  push:
    branches: '**'
    paths:
      - '**.cs'
      - '**.csproj'
      
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: "echo something"
      run: echo something
      
