name: Ministerio de Turismo

on:
  push:
    branches: '**'
    paths:
      - '**.cs'
      - '**.csproj'
  pull_request:
    branches: '**'
    paths:
      - '**.cs'
      - '**.csproj'
      
jobs:
  build:
    runs-on: windows-latest
    run: echo HOLA

